 version: 2
 jobs:
   build:
     working_directory: ~/circleci-quorem
     docker:
       - image: circleci/python:3.6.4
         environment: 
           PIPENV_VENV_IN_PROJECT: true
     steps:
       - checkout
       - run: echo "Setup config"
	
